## DDos Balanced

In [1]:
import numpy as np
import pandas as pd

### Overview data

In [2]:
df = pd.read_csv('../dataset/ddos_balanced/final_dataset.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12794627 entries, 0 to 12794626
Data columns (total 85 columns):
 #   Column             Dtype
---  ------             -----
 0   Unnamed: 0         int64
 1   Flow ID            object
 2   Src IP             object
 3   Src Port           int64
 4   Dst IP             object
 5   Dst Port           int64
 6   Protocol           int64
 7   Timestamp          object
 8   Flow Duration      int64
 9   Tot Fwd Pkts       int64
 10  Tot Bwd Pkts       int64
 11  TotLen Fwd Pkts    float64
 12  TotLen Bwd Pkts    float64
 13  Fwd Pkt Len Max    float64
 14  Fwd Pkt Len Min    float64
 15  Fwd Pkt Len Mean   float64
 16  Fwd Pkt Len Std    float64
 17  Bwd Pkt Len Max    float64
 18  Bwd Pkt Len Min    float64
 19  Bwd Pkt Len Mean   float64
 20  Bwd Pkt Len Std    float64
 21  Flow Byts/s        float64
 22  Flow Pkts/s        float64
 23  Flow IAT Mean      float64
 24  Flow IAT Std       float64
 25  Flow IAT Max       float64
 26  Flow IAT Min       float64
 27  Fwd IAT Tot        float64
 28  Fwd IAT Mean       float64
 29  Fwd IAT Std        float64
 30  Fwd IAT Max        float64
 31  Fwd IAT Min        float64
 32  Bwd IAT Tot        float64
 33  Bwd IAT Mean       float64
 34  Bwd IAT Std        float64
 35  Bwd IAT Max        float64
 36  Bwd IAT Min        float64
 37  Fwd PSH Flags      int64
 38  Bwd PSH Flags      int64
 39  Fwd URG Flags      int64
 40  Bwd URG Flags      int64
 41  Fwd Header Len     int64
 42  Bwd Header Len     int64
 43  Fwd Pkts/s         float64
 44  Bwd Pkts/s         float64
 45  Pkt Len Min        float64
 46  Pkt Len Max        float64
 47  Pkt Len Mean       float64
 48  Pkt Len Std        float64
 49  Pkt Len Var        float64
 50  FIN Flag Cnt       int64
 51  SYN Flag Cnt       int64
 52  RST Flag Cnt       int64
 53  PSH Flag Cnt       int64
 54  ACK Flag Cnt       int64
 55  URG Flag Cnt       int64
 56  CWE Flag Count     int64
 57  ECE Flag Cnt       int64
 58  Down/Up Ratio      float64
 59  Pkt Size Avg       float64
 60  Fwd Seg Size Avg   float64
 61  Bwd Seg Size Avg   float64
 62  Fwd Byts/b Avg     int64
 63  Fwd Pkts/b Avg     int64
 64  Fwd Blk Rate Avg   int64
 65  Bwd Byts/b Avg     int64
 66  Bwd Pkts/b Avg     int64
 67  Bwd Blk Rate Avg   int64
 68  Subflow Fwd Pkts   int64
 69  Subflow Fwd Byts   int64
 70  Subflow Bwd Pkts   int64
 71  Subflow Bwd Byts   int64
 72  Init Fwd Win Byts  int64
 73  Init Bwd Win Byts  int64
 74  Fwd Act Data Pkts  int64
 75  Fwd Seg Size Min   int64
 76  Active Mean        float64
 77  Active Std         float64
 78  Active Max         float64
 79  Active Min         float64
 80  Idle Mean          float64
 81  Idle Std           float64
 82  Idle Max           float64
 83  Idle Min           float64
 84  Label              object
dtypes: float64(45), int64(35), object(5)
memory usage: 8.1+ GB

#### Data shape

In [4]:
df.shape

(12794627, 85)

### Data preprocessing

#### Remove nullable value

In [5]:
# List nullable value
df.isnull().sum()

Unnamed: 0    0
Flow ID       0
Src IP        0
Src Port      0
Dst IP        0
             ..
Idle Mean     0
Idle Std      0
Idle Max      0
Idle Min      0
Label         0
Length: 85, dtype: int64

#### => Dont have any nullable value to remove

In [6]:
df.head()

,Unnamed: 0,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,624,192.168.4.118-203.73.24.75-4504-80-6,192.168.4.118,4504,203.73.24.75,80,6,12/06/2010 08:34:32 AM,3974862,29,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ddos
1,625,192.168.4.118-203.73.24.75-4504-80-6,192.168.4.118,4504,203.73.24.75,80,6,12/06/2010 08:34:36 AM,63,1,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ddos
2,626,192.168.4.118-203.73.24.75-4505-80-6,192.168.4.118,4505,203.73.24.75,80,6,12/06/2010 08:34:36 AM,476078,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ddos
3,627,192.168.4.118-203.73.24.75-4505-80-6,192.168.4.118,4505,203.73.24.75,80,6,12/06/2010 08:34:37 AM,151,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ddos
4,628,192.168.4.118-203.73.24.75-4506-80-6,192.168.4.118,4506,203.73.24.75,80,6,12/06/2010 08:34:37 AM,472507,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ddos